kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aro-files-storage-clusterrollebinding
subjects:
  - kind: ServiceAccount
    name: persistent-volume-binder
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:azure-file-volume-binder
